
INSERT INTO estados(cve_ent, nom_ent, nom_abr, id_pais) VALUES ('01', 'Aguascalientes', 'Ags.', 'MX');
INSERT INTO estados(cve_ent, nom_ent, nom_abr, id_pais) VALUES ('02', 'Baja California', 'BC', 'MX');
INSERT INTO estados(cve_ent, nom_ent, nom_abr, id_pais) VALUES ('03', 'Baja California Sur', 'BCS', 'MX');
INSERT INTO estados(cve_ent, nom_ent, nom_abr, id_pais) VALUES ('04', 'Campeche', 'Camp.', 'MX');
INSERT INTO estados(cve_ent, nom_ent, nom_abr, id_pais) VALUES ('05', 'Coahuila de Zaragoza', 'Coah.', 'MX');
INSERT INTO estados(cve_ent, nom_ent, nom_abr, id_pais) VALUES ('06', 'Colima', 'Col.', 'MX');
INSERT INTO estados(cve_ent, nom_ent, nom_abr, id_pais) VALUES ('07', 'Chiapas', 'Chis.', 'MX');
INSERT INTO estados(cve_ent, nom_ent, nom_abr, id_pais) VALUES ('08', 'Chihuahua', 'Chih.', 'MX');
INSERT INTO estados(cve_ent, nom_ent, nom_abr, id_pais) VALUES ('09', 'Distrito Federal', 'DF', 'MX');
INSERT INTO estados(cve_ent, nom_ent, nom_abr, id_pais) VALUES ('10', 'Durango', 'Dgo.', 'MX');
INSERT INTO estados(cve_ent, nom_ent, nom_abr, id_pais) VALUES ('11', 'Guanajuato', 'Gto.', 'MX');
INSERT INTO estados(cve_ent, nom_ent, nom_abr, id_pais) VALUES ('12', 'Guerrero', 'Gro.', 'MX');
INSERT INTO estados(cve_ent, nom_ent, nom_abr, id_pais) VALUES ('13', 'Hidalgo', 'Hgo.', 'MX');
INSERT INTO estados(cve_ent, nom_ent, nom_abr, id_pais) VALUES ('14', 'Jalisco', 'Jal.', 'MX');
INSERT INTO estados(cve_ent, nom_ent, nom_abr, id_pais) VALUES ('15', 'México', 'Mex.', 'MX');
INSERT INTO estados(cve_ent, nom_ent, nom_abr, id_pais) VALUES ('16', 'Michoacán de Ocampo', 'Mich.', 'MX');
INSERT INTO estados(cve_ent, nom_ent, nom_abr, id_pais) VALUES ('17', 'Morelos', 'Mor.', 'MX');
INSERT INTO estados(cve_ent, nom_ent, nom_abr, id_pais) VALUES ('18', 'Nayarit', 'Nay.', 'MX');
INSERT INTO estados(cve_ent, nom_ent, nom_abr, id_pais) VALUES ('19', 'Nuevo León', 'NL', 'MX');
INSERT INTO estados(cve_ent, nom_ent, nom_abr, id_pais) VALUES ('20', 'Oaxaca', 'Oax.', 'MX');
INSERT INTO estados(cve_ent, nom_ent, nom_abr, id_pais) VALUES ('21', 'Puebla', 'Pue.', 'MX');
INSERT INTO estados(cve_ent, nom_ent, nom_abr, id_pais) VALUES ('22', 'Querétaro', 'Qro.', 'MX');
INSERT INTO estados(cve_ent, nom_ent, nom_abr, id_pais) VALUES ('23', 'Quintana Roo', 'Q. Roo', 'MX');
INSERT INTO estados(cve_ent, nom_ent, nom_abr, id_pais) VALUES ('24', 'San Luis Potosí', 'SLP', 'MX');
INSERT INTO estados(cve_ent, nom_ent, nom_abr, id_pais) VALUES ('25', 'Sinaloa', 'Sin.', 'MX');
INSERT INTO estados(cve_ent, nom_ent, nom_abr, id_pais) VALUES ('26', 'Sonora', 'Son.', 'MX');
INSERT INTO estados(cve_ent, nom_ent, nom_abr, id_pais) VALUES ('27', 'Tabasco', 'Tab.', 'MX');
INSERT INTO estados(cve_ent, nom_ent, nom_abr, id_pais) VALUES ('28', 'Tamaulipas', 'Tamps.', 'MX');
INSERT INTO estados(cve_ent, nom_ent, nom_abr, id_pais) VALUES ('29', 'Tlaxcala', 'Tlax.', 'MX');
INSERT INTO estados(cve_ent, nom_ent, nom_abr, id_pais) VALUES ('30', 'Veracruz de Ignacio de la Llave', 'Ver.', 'MX');
INSERT INTO estados(cve_ent, nom_ent, nom_abr, id_pais) VALUES ('31', 'Yucatán', 'Yuc.', 'MX');
INSERT INTO estados(cve_ent, nom_ent, nom_abr, id_pais) VALUES ('32', 'Zacatecas', 'Zac.', 'MX');
